GET http://localhost:3000/songs

###
POST http://localhost:3000/songs.json
content-type: application/json

{
  "title": "Cold Heart",
  "album": "Single",
  "artist": "Elton John/Dua Lipa",
  "year": 2021
}

###
GET http://localhost:3000/songs/5.json

###
PATCH http://localhost:3000/songs/5.json
content-type: application/json

{
  "title": "Stay",
  "album": "Single",
  "artist": "Justin Bieber/The Kid LAROI",
  "year": 2021
}